### ISSUE TITLE
Error message when I try to goto the terminal.

### ISSUE THREAD

**Issue by Dink4n** [ThePrimeagen/harpoon#1]
Hi, Everything was working until I exited the terminal and tried GotoBuffer to that terminal. When doing so, I got:
![image](https://user-images.githubusercontent.com/59307910/98764041-f8574180-2400-11eb-833a-1784cf7b86a7.png)

**Comment by JimboKearn** [comment]
I already resolved the issue and made it vim compatible.
Should I make a PR.

**Comment by ThePrimeagen** [comment]
115% you should make a PR!

I would love to have this be vim compat as well.

**Comment by ThePrimeagen** [comment]
Btw, I think I am going to rewrite this and make it better shortly!  So if you don't do anything, i'll be doing something shortly.

**Comment by ThePrimeagen** [comment]
I have changed all the things so that this should not be an issue.

My guess is that this is old and is no longer an issue, if you wish to give it another try, cheers.

also, I have integrated a marking mechanism.  Its purdy fancy.  But there may be an issue on empty projects i'll try to take care of shortly.

For now I am going to close this.
