### ISSUE TITLE
Codebase cleanup

### ISSUE THREAD

**Issue by RaafatTurki** [ThePrimeagen/harpoon#117]
I've been using harpoon for a while now and it has sped up my workflow by a lot, however this one bit is missing (or so I believe) which is the ability to navigate back to the last file/terminal you've opened.

This opens so many possibilities, in my case it would give me the ability to do this
nmap `term.nav_last()` and tmap `ui.nav_last()` to the same key
now whenever I press that key it switches me between file and terminal

I've tried to take a stab at It and my stab did work but it's not the right way to stab it :(
I've tried doing it the right way but I've found the codebase a little confusing/inconsistent right now for example:

in `ui.select_menu_item()` an `idx` is defined and passed to `ui.nav_file()` which now refers to it as `id` and uses it to create an another `idx`

also some module functions are defined as `function M.name(args)` while others as `M.name = function(args)`

and a general lack of documentation, I wanted to also implement `ui.nav_next()` and `ui.nav_prev()` but I've found it to be already implemented after digging through the source code, also what in the deuce is `c.c`

Point is, I like this plugin and want to see it flourish and I do understand it's still in beta but it doesn't have to be.
I would do a cleanup PR if it's a welcome change.

**Comment by ThePrimeagen** [comment]
yayaya!

Totally agree.  Unfortunately its grown in a way I didn't even see coming :)

But what needs to happen to this is that the list item needs to be pulled out of the 2 / 3 places its currently being "duplicated" at.  I have allowed it to happen just because these are asked for features without the time to make them into what I want.  That is my first and most important task to take.

If you wish to take a stab at that, I would be glad to review/approve.

As far as some simple namings etc, we can do the clean ups on those once we can have 1 ~~class~~ table that is the virtual list.  And I bet that if we did the refactoring, it would also clean up the naming by accident.

Lastly, the thing you want to do would be very easy to do with a proper list table pulled out and created as it would be a single implementation for all of them.

**Comment by ThePrimeagen** [comment]
I would also love to see this cleanup happen after #103 

This was my plan as it introduces the 3rd list item.  Rule of three bay bee.

**Comment by pranavrao145** [comment]
@ThePrimeagen, do you mind elaborating a bit on what you mean by the "virtual list"? I've looked through the source code and found some duplicated logic, but I can't seem to find the duplicated list logic you're talking about.

**Comment by RaafatTurki** [comment]
@pranavrao145 it's not implemented yet, as I understand its purpose would be to represent a unified single source of truth to all the marks within any given project.

on a side note could you specific where that duplicate logic resides, I'm doing project cleanup now that #103 is merged and such detail would help a lot.

**Comment by ThePrimeagen** [comment]
Sorry, with the fam, will elaborate more shortly

**Comment by pranavrao145** [comment]
> on a side note could you specify where that duplicate logic resides, I'm doing project cleanup now that #103 is merged and such detail would help a lot.

@RaafatTurki sure, I was talking about the duplicate logic in tmux.lua and term.lua. I was thinking that should be refactored to an external term utils module.

**Comment by RaafatTurki** [comment]
@pranavrao145 true, those two have a lot in common primarily because that PR aimed to be a drop in replacement
