### ISSUE TITLE
Attempt to open quick menu entry in current empty buffer if possible

### ISSUE THREAD

**Issue by atchim** [ThePrimeagen/harpoon#119]
Currently, `harpoon` opens quick menu entries in a new buffer, even if the current buffer is empty. I think it would be better if `harpoon` first attempted to open the entry in the current empty buffer if possible, similarly to what `:edit` does.

**Comment by ThePrimeagen** [comment]
Just to get things straight.  Are you saying that harpoon opens from menu with a split?  In other words, could you be a bit more clear on what you are saying.

**Comment by atchim** [comment]
@ThePrimeagen, let's suppose that I opened Neovim and executed the following commands.

```vim
ls
"  1 %a   "[No Name]"                    line 1

" Add a mark to file `foo.txt`.
lua require'harpoon.mark'.add_file'foo.txt'

" Then navigate to it.
lua require'harpoon.ui'.nav_file(1)

ls
"  1 %a   "[No Name]"                    line 1
"  2 %a   "foo.txt"                      line 1
```

As you can see, `harpoon` created another buffer to open `foo.txt` even with the current buffer being empty.

**Comment by carlosgarciafm** [comment]
I think the issue lies here in how `harpoon` loads marks using: https://github.com/ThePrimeagen/harpoon/blob/38715a8f8bab8f12622630799c750834a98da757/lua/harpoon/ui.lua#L167

In the current implementation, if a buffer containing the file does not exist, a new one is created and its id is returned.

Although a bit ugly, a quick fix would be to do as you suggest, use `:edit`.
```lua
local buf_id = vim.fn.bufnr(mark.filename)
if buf_id == -1 then
    vim.cmd(string.format("%s %s", "edit", mark.filename))
    buf_id = vim.fn.bufnr(mark.filename)
end
```
