### ISSUE TITLE
Jump to window if file is already open instead of changing current window

### ISSUE THREAD

**Issue by micakce** [ThePrimeagen/harpoon#203]
Sometimes I have three windows opened, would be nice when `nav_file(x)` it would jump to the window with the file opened instead of changing the current window to the same file that is open in the window next to it.

**Comment by matu3ba** [comment]
This would require additional configuration, because having multiple windows side by side is a normal use case. Think of multiple similar code below and above and you only want to quickly check some global thing you wrote to replace something etcetc.

You could write the wrapper yourself, so I would suggest to change the title to "document how to access things in harpoon" to simplify configuration. See #198.
