### ISSUE TITLE
Harpoon menu conflicts with LSPsaga popup 

### ISSUE THREAD

**Issue by LeVuMinhHuy** [ThePrimeagen/harpoon#267]
When I open `Lspsaga lsp_finder`, harpoon menu also shows up. Can anyone please help me with this, many thanks

![image](https://user-images.githubusercontent.com/36370320/227147812-338e6ba7-9067-43dd-8551-79a3a2ea0f80.png)

**Comment by timothyis** [comment]
Is this when you're using a default keymap? Or in any scenaro?

If it's a keymap conflict and you're using a Lua configuration for Neovim, you can redefine the keymaps for either plugin:
- Default lspsaga keymaps (use as an example to set your own): https://github.com/glepnir/lspsaga.nvim#example-configuration
- Use harpoon's API with Neovim keymap settings: https://github.com/ThePrimeagen/harpoon#-harpooning, https://neovim.io/doc/user/lua-guide.html#lua-guide-mappings-set

**Comment by LeVuMinhHuy** [comment]
@timothyis I don't think it's a keymap conflict

```
-- Harpoon
vim.keymap.set("n", "<C-e>", ui.toggle_quick_menu, {silent = true, noremap = true})

-- LSP Saga
vim.keymap.set("n", "gh", "<cmd>Lspsaga lsp_finder<CR>", { silent = true })
```

**Comment by nguyenanhhao221** [comment]
Also experiencing the same problem. Have to switch back to native lsp hover rather than lsp saga

**Comment by fcarvalhopacheco** [comment]
Same here. 

My keymap is for harppon is `vim.keymap.set("n", "<C-m>", ui.toggle_quick_menu)` . It's even weird cause the menu also opens when a press `return`...

**Comment by JasonPanosso** [comment]
Same issue, happens 90% of the time I use lspsaga lsp_finder.

**Comment by koyuncukaan** [comment]
Having the same issue. It's not conflicting with keymap. It probably something else. Here is my error and stacktrace
`Error detected while processing CursorMoved Autocommands for "<buffer=10>":
Error executing lua callback: ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:497: Line number outside range
stack traceback:
        [C]: in function 'nvim_buf_add_highlight'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:497: in function <...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:458>`

**Comment by nbili** [comment]
Same issue

**Comment by JasonPanosso** [comment]
Possibly related?
https://github.com/nvimdev/lspsaga.nvim/issues/1070

**Comment by JasonPanosso** [comment]
Turns out this issue and the one I linked in my previous comment are [related](https://github.com/nvimdev/lspsaga.nvim/issues/1070#issuecomment-1559890327). 

All of us(besides one) use `<C-e>` to open harpoon(This is the binding that Prime uses and it seemed sane). However, Lspsaga seemingly inputs `<C-e>` when popup windows are created/rendered. I checked @nguyenanhhao221 & @koyuncukaan and verified that they are also using `<C-e>`, however I do not understand how @fcarvalhopacheco's issue with their `<C-m>` binding fits into this. I do know that `<C-m>` is default bound to `<CR>` in vim/linux/unix/dos, and maybe that's somehow causing the problem? Honestly stumped on that one.

I've alerted the lead dev of Lspsaga, and hopefully this gets fixed soon. For the time being if you wish to continue using Lspsagas call hierarchy/peek definition/lsp_finder you can not rebind `<C-e>` in general as the default vim binding is required for Lspsaga to function. 

Lastly, @LeVuMinhHuy could you please close this issue as it pertains to Lspsaga and not harpoon?
