### ISSUE TITLE
#320 is still relevant to harpoon2

### ISSUE THREAD

**Issue by name-snrl** [ThePrimeagen/harpoon#383]
As I see, by default, when you select a mark, buffer is created with `vim.fn.bufnr()`:

https://github.com/ThePrimeagen/harpoon/blob/b66e92d4f56d471630fddfcbe89880e9de783367/lua/harpoon/config.lua#L114-L119

But there are 2 problems:
- if the file hasn't been opened before, it inherits the harpoon buffer options
- it's marked as unloaded, and if I try to jump to it using telescope buffers, it doesn't show up in list

**Comment by ThePrimeagen** [comment]
very interesting.

could you explain how you are getting to this?  Because "inherits the harpoon buffer options" makes me think that this is a selecting file from UI action?  else you would be opening the buffer from just a regular file (using `select`).

this is a great catch and obviously need to ensure that the buffer is opened as a proper file with whatever missing settings

**Comment by name-snrl** [comment]
> could you explain how you are getting to this?

Yeah, sorry, thought the explanation from #320 enough. Oh wait, first of all we need a mapping that will open a buffer with `vsplit` option, as in harpoon1. To get this you need to apply #382 and patch (for some reason github won't let me upload the .patch file) from https://github.com/ThePrimeagen/harpoon/pull/382#issuecomment-1843092989.

Now to reproduce:
- set nonumber in your config, because harpoon window sets it
- add some marks
- restart nvim to make sure none of the buffers have been opened in the current instance
- open the menu, press <C-v> to open any mark in vertical split
- openned split will have numbers

**Comment by name-snrl** [comment]
btw, I'm not sure about the other options, but I think the split will inherit all the harpoon window options

**Comment by name-snrl** [comment]
#392
