### ISSUE TITLE
ZZ should :wq current Harpoon window

### ISSUE THREAD

**Issue by Mathijs-Bakker** [ThePrimeagen/harpoon#82]
## Expected behavior:
`<S>zz` should write and close the current open window.

## Actual behavior
`<S>zz` closes window but **doesn't write** modifications.

**Comment by asbjornhaland** [comment]
From nvim docs: ZZ Write current file, if **modified**, and quit (same as....

We set the modified flag to always be false so that you can always `:q`, and use `:wq` when you want to save the changes.

@ThePrimeagen : `save_on_toggle` is only used for calling toggle and not when using `ZZ`. Must we create a local remap of `ZZ` to use `close_menu(true)`(force save)?

**Comment by Mathijs-Bakker** [comment]
Ah! you are suppressing a **No write since last change warning** here by setting the nomodified option.  
To make closing the pop window nondisruptive.
```lua
"autocmd BufModifiedSet <buffer=%s> set nomodified", Harpoon_bufh
```
Yes, then you could create a local map... `:no <buffer> <S>zz ...`

But it does violate the purpose of the `nomodified` arg.

**Comment by asbjornhaland** [comment]
Correct.

**Comment by Mathijs-Bakker** [comment]
This is solved somewhere along the way.
Closing...
